spring:
  cloud:
    gateway:
        discovery:
          locator:
            enabled: true
        routes:
          - id : r1
            uri : lb://CUSTOMER-SERVICE
            predicates:
              - Path=/customers/**
          - id : r2
            uri : lb://ACCOUNT-SERVICE
            predicates:
              - Path=/accounts/**
  application:
    name: gateway-service
server:
  port: 8888
